### ISSUE TITLE
[Feature] - Block Storage in More Locations?

### ISSUE THREAD

**Issue by orware** [vultr/condor#8]
This kind of a dumb request, but just hoping someone else might see it since I know I've asked support about this in the past already.

I've been hoping to hear more about expansions of block/object storage into locations outside of New Jersey for some time...I'd love to be able to try out some of this new Kubernetes stuff but wouldn't be able to truly utilize it in production unless a West Coast location (preferably the LA region for us) was available for those products.

I'll keep my fingers crossed that the team is already hard at work trying to add those features in other locations already!

**Comment by ddymko** [comment]
Thanks for the suggestion! Because this is isn't [necessarily a bug or software feature in] Condor product, I've forwarded your question to our sales team. They will reach out to you directly in our support system.
