### ISSUE TITLE
How do I get kubeconfig file for the Kubernetes Cluster generated with https://github.com/vultr/condor?

### ISSUE THREAD

**Issue by nubela** [vultr/condor#9]
I just created a k8s cluster but I can't get the credentials to connect to it.

Please advise, thank you!

**Comment by ddymko** [comment]
@nubela I just deployed a cluster using condor and took the `admin-default.config` and moved it to `~./kube` as a file called `config` and it is working fine.

That is all that should be done to connect to your cluster with `kubectl`
